### ISSUE TITLE
✨[Polish] Improve Language Switching 

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-ios#70]
## Overview
The current implementation of iOS language switching in Litewallet works but ti relies on the user to return to the app.  Apple made this process difficult and it should be more continous and less disjointed. 
### Why?
This newer iOS versions may allow a better solution

### What?
Look of options: https://apple.stackexchange.com/questions/231000/ios-how-to-set-language-of-app-independent-of-iphone-ipad-language/371690#371690

**Describe alternatives you've considered**

**Additional context**
 

### Definition of Done
- [x] Pick a more updated language capability in app
- [x] Implement
- [x] Test and submit PR

## UI Changes
Show the before and after
|**Before**|**After**|
|----------|---------|
 |![ChangeLanguage](https://user-images.githubusercontent.com/2899463/123003578-4840b280-d3ab-11eb-848c-09e89e23b8c8.gif)||

**Comment by kcw-grunt** [comment]
@Iferencak : My guess is you may already have an elegant solution to this problem.

**Comment by Iferencak** [comment]
@kcw-grunt 
Unfortunately, best solution by apple is still to send the user out of the app and in the "Settings". 

However, I agree with you that this is not ideal as it takes the user out of the app.
There wasn't really an elegant solution in this case, but I think that what I have done is X times better than before. 
I had to change the way strings are localised a bit, because if they are a static property in the enum, once it was initialised, it couldn't be changed. 

| Before  | After |
| ------------- | ------------- |
| ![](https://user-images.githubusercontent.com/2899463/123003578-4840b280-d3ab-11eb-848c-09e89e23b8c8.gif) | ![](https://user-images.githubusercontent.com/19799406/204139673-e59c0b65-9c46-492e-8606-05adadff2b47.gif) |


Because it was a quick fix, I also took the liberty and fixed the transparent navigation bar issue.
| Before  | After |
| ------------- | ------------- |
| ![](https://user-images.githubusercontent.com/19799406/204140129-08f0ea6f-c5e9-49ab-a68e-925ef8a989e3.JPG) | ![](https://user-images.githubusercontent.com/19799406/204140147-96731c85-874a-4011-b08f-f95d91bee89e.jpg) |
